export const ROUTES = {
    LOGIN: 'LOGIN',
    HOME: 'HOME',
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    ONBOARDING: 'ONBOARDING',
    TABS: 'TABS',
    DRAWER: 'DRAWER',
    ROSTER: 'ROSTER',
    INBOX: 'INBOX',
    INBOX_DETAILS: 'INBOX_DETAILS',
    MED_ATTESTATION: 'MED_ATTESTATION',
    NOTES:'NOTES',
    PROFILE: 'PROFILE',
    ROSTER_DETAILS: 'ROSTER_DETAILS',
    MDEAFORM: 'MDEAFORM',
    
}